### ISSUE TITLE
HttpResponseHeader and empty `reason`

### ISSUE THREAD

**Issue by eikek** [Spinoco/protocol#14]
Hi, 
I wrote a little http server using fs2-http and then a client to consume this service with fs2-http, too. But the client failed to parse the response generated from my fs2-http endpoint. The problem was, that I was too lazy to think about the `reason` line in the http status line and put an empty string in it:

```
HttpResponse(
      HttpResponseHeader(
        status = status,
        reason = "",
        headers = Nil),
      Stream.empty
    )
```

Most other http parsers I used with this endpoint (like browsers and Elm http) parsed the response without problems, but the `HttpResponseHeaderCodec` expects a reason after the status code. Once I used `reason = status.label` in the above snippet, my problems were solved. But it took a while to figure that out :-)

So my question is, whether we can improve the api in that it either is not possible to specify an empty reason or it I would also be fine with throwing an exception. Or make the reason line optional in the response parser? (I'm not sure about the exact spec here)

**Comment by pchlupacek** [comment]
@eikek my first thought will be to be able to parse whatever we produce, so I consider this as a bug. Will need to check that with the standard, if there is strict definition of that. 
Also if standrard would be strict we can alter the encoder so it will fail whenever the empty string is encoded.

**Comment by eikek** [comment]
@pchlupacek thanks, that sounds reasonable to me
