### ISSUE TITLE
don't use reflection in headers

### ISSUE THREAD

**Issue by fommil** [Spinoco/protocol#15]
this could be done with compiletime evidence
https://github.com/Spinoco/protocol/blob/master/http/src/main/scala/spinoco/protocol/http/header/DefaultHeader.scala

e.g. `shapeless.Typeable`

**Comment by fommil** [comment]
Another way of doing this would be to use http://co.ntextu.al/

You could do a lot of checking at compiletime and use interpolated strings without fear
would save creating all those classes! e.g. syntax like 

```scala
header"X-Forwarded-For: $wibble"
```

and have it check the syntax of the header, and that the `$wibble` has a `HttpHeaderEncode` typeclass instance (I'm assuming you have something like that... I don't know the API well enough). You could even enforce that headers constructed this way are a value picked from a `Set[String]`.

// @propensive

**Comment by pchlupacek** [comment]
@fommil can you please give an example // ideally submit a PR to solve this issue ?

**Comment by fommil** [comment]
it would be a shame not to direct you to the beautiful contextual website :smile:, worth reading even if you have no intention of doing anything with it. I guarantee you'll find *some* usecase for it in your work... http://co.ntextu.al/

**Comment by AdamChlupacek** [comment]
I do like the contextual, but only as a syntax help. Since completely dropping the classes in my opinion would make it much harder in terms of figuring out what header can have what fields.

I do agree we should drop the reflection in favour if `shapeless.Typeable`, will get a PR together for it.

**Comment by propensive** [comment]
Thanks for the tag, @fommil!

Contextual is quite capable of only allowing certain types to be substituted in certain positions, allows them to be formatted however you want, and lets you return custom compile-time error messages if something's not right. Not sure I fully understood what "dropping the classes" means here, but happy to elaborate on Contextual, if necessary.

**Comment by propensive** [comment]
As an example, you could have
```
val time = "12 o'clock"
header"Expires: $time"
```
return a failure saying something like,
```
header"Expires: $time"
                 ^ the `Expires` header expects a Date or Int
```

**Comment by AdamChlupacek** [comment]
It point is that without having the actual header classes the users wont know what types they should include until they compile right?

**Comment by fommil** [comment]
I'm pretty sure most developers are looking at the http spec rather than the spinoco code...

**Comment by pchlupacek** [comment]
@propensive @fommil essentially if I am following correctly you suggesting to encode these as Evidences that that may / may not be encoded to HttpHeader instead of bunch of case classes correct? 

If so, how long you think it would be to convert current case class api to that encoding? Could you do that? 

Reason why I am asking is that I don't want to delay fs2(0.10) version of fs2-http, and don't want to introduce that significant change after it will be out.

**Comment by pchlupacek** [comment]
Also one small remark here, I understand how this work, when you constructing the new headers, but then how you deconstruct them? I.e. can you show the evidence that guaranties that from Expired header I can only get a date?

**Comment by propensive** [comment]
One way would be to have a sealed `Header` trait, with different case class subtypes for each header you want to support, plus maybe a generic `X-Header` case class. Contextual runs as a macro, but doesn't expose much of the information you would need to inspect the case class types automatically, so there would be some duplication of header structure in both the parser and the case classes. There are ways around this, though.

You could then pattern-match on the case classes.

Scala (not Contextual) does have support for interpolated-string extractors, but they're quite complex to implement. Maybe I'll get a chance to do it some time...

**Comment by AdamChlupacek** [comment]
Great, thats about how our `Header` structure is right now. As such I see this only as a great syntactic sugar, would be great to have at some point in the future ( any PRs would be appreciated). But this is not blocking release of next protocols version.
