### ISSUE TITLE
Arbitrary uri schemes

### ISSUE THREAD

**Issue by eikek** [Spinoco/protocol#20]
In my application, I get requests from mobile browsers that specify referrer urls with _some_ http scheme, for example 
```
Referer: android-app://com.google.android.gm
```
This will not parse and all users using this mobile browser can't use the application. What do you think about adding a „generic scheme” or some other fallback variant? I may be mistaken, but I think the spec is open in that regard (allowing any alphanumeric value, regarding [this spec](https://tools.ietf.org/html/rfc3986#section-3.1)).

**Comment by AdamChlupacek** [comment]
As we are indeed implementing the ref you specified we will be changing this, probably in to some case class encoding. Sadly this change will not be binary compatible :/ I would like to have this done before we release fs2-http for fs2 0.10.
