### ISSUE TITLE
parsing some valid uris fails

### ISSUE THREAD

**Issue by eikek** [Spinoco/protocol#5]
Hello,

I'm coming from fs2-http (thanks btw for both!) and some of my requests didn't made it to my server. I found two things. For example a trailing slash is required:

```
scala> spinoco.protocol.http.Uri.parse("http://bla.com")
res5: scodec.Attempt[spinoco.protocol.http.Uri] = Failure(Expected value with optional parameter, got none)

scala> spinoco.protocol.http.Uri.parse("http://bla.com/")
res6: scodec.Attempt[spinoco.protocol.http.Uri] = Successful(Uri(http,HostPort(bla.com,None),Path(true,false,WrappedArray()),Query(List())))
```
Or, query parameters must have a value:

```
scala> spinoco.protocol.http.Uri.parse("http://bla.com/?a=")
res7: scodec.Attempt[spinoco.protocol.http.Uri] = Failure(0: Expected tuple, got List(Right(a)))

scala> spinoco.protocol.http.Uri.parse("http://bla.com/?a=1")
res8: scodec.Attempt[spinoco.protocol.http.Uri] = Successful(Uri(http,HostPort(bla.com,None),Path(true,false,WrappedArray()),Query(List((a,1)))))
```

Does this make sense, or am I missing something here?

**Comment by pchlupacek** [comment]
eikek yes, both of your observations are correct. Not sure what Uri Http standards are telling us there. Can you please verify? I think definitely the http://bla.com and http://bla.com/ shall parse to different Uri, and both of them shall parse. Not sure on query parameters though. 
Can you please find reference on correct Uri encoding, then we'll decide on correct fix approach ok ?

**Comment by eikek** [comment]
If I understand correctly, an URI doesn't care about the format of its query, everything between first `?` and first `#` is the “query string”. See [0] and [1].

I think, the key/value pair thing is coming from HTML (forms) and there is no real specification, as far as I can see. There is [2] just explaining how a user agent should create a uri from a form element. There is no explicit mention about empty parameters. But thinking from there, an empty value seems valid to me. On [stackoverflow](http://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value) a guy says that some asp version doesn't parse it. I _think_ most java/jvm-related frameworks/servers out there do allow it. For me fs2-http was the first I encountered that didn't parse it (I think, play framework does and spray does/did, for example). 

Regarding the trailing slash: If I understand [this RFC](https://tools.ietf.org/html/rfc3986#section-3) correctly, it may be empty if an authority is present. So the difference (between the two cases above) would be, that there is no path at all or it is the root path.

wdyt?

[0] https://tools.ietf.org/html/rfc3986#section-3.4
[1] https://tools.ietf.org/html/rfc7320#section-2.4
[2] https://www.w3.org/TR/1999/REC-html401-19991224/interact/forms.html#submit-format

**Comment by pchlupacek** [comment]
@eikek I think I am with you on this one. You are welcome to make PR to fix this.

**Comment by pchlupacek** [comment]
@eikek Thanks for fixes. I believe with your last fix this can be closed ?

**Comment by eikek** [comment]
@pchlupacek you are welcome! Yes, this is closed. Thank you!
